trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'Self-Hosted-Pool'

    steps:

    # 1️⃣ Download SSH Public Key from Secure Files
    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'azure_vm_key.pub'
      displayName: 'Download SSH Public Key'

    # 2️⃣ Copy SSH key into Terraform module folder

    - script: |
        echo "Creating compute module directory if it doesn't exist..."
        mkdir -p $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/

        echo "Copying SSH public key into Terraform module"
        mkdir -p ~/.ssh
        cp $(download_ssh_key.secureFilePath) ~/.ssh/azure_vm_key.pub
        cp $(download_ssh_key.secureFilePath) $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/azure_vm_key.pub
        echo "Listing contents of azure/modules/compute/"
        ls -al $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/
      displayName: 'Prepare SSH Public Key for Terraform'

    # 3️⃣ Download Terraform variable file (dev.tfvars.txt) securely
    - task: DownloadSecureFile@1
      name: download_tfvars
      inputs:
        secureFile: 'dev.tfvars.txt'
      displayName: 'Download Terraform Variable File'

    # 4️⃣ Copy & rename the secure file into Terraform working directory
    - script: |
        echo "Copying tfvars file to Terraform working directory..."
        cp $(download_tfvars.secureFilePath) $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars
        echo "Secure file copied and renamed successfully:"
        ls -al $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars
      displayName: 'Prepare dev.tfvars for Terraform'

    # 5️⃣ Terraform Init, Plan, and Apply
    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, and Apply'
      inputs:
        azureSubscription: 'arm-epicbook-spn'  # Your service connection
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/epicbook-infra
        inlineScript: |
          echo "Initializing Terraform..."
          terraform init -input=false

          echo "Planning Terraform changes..."
          terraform plan -input=false -var-file=dev.tfvars

          echo "Applying Terraform..."
          terraform apply -input=false -auto-approve -var-file=dev.tfvars

    # 6️⃣ Optional: Clean up secure files after use
    - script: |
        echo "Cleaning up secure files..."
        rm -f ~/.ssh/id_rsa.pub
        rm -f $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars
      displayName: 'Clean Up Secure Files'