trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'Self-Hosted-Pool'

    steps:

    # =========================
    # 1️⃣ Checkout repo
    # =========================
    - checkout: self
      clean: true
      displayName: 'Checkout Epicbook Infra Repo'

    # =========================
    # 2️⃣ Download SSH public key from Secure Files
    # =========================
    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'azure_vm_key.pub'
      displayName: 'Download SSH Public Key'
      # After this step, the SSH key is at: $(download_ssh_key.secureFilePath)

    # =========================
    # 3️⃣ Copy SSH key into Terraform module
    # =========================
    - script: |
        echo "Creating module folder if it doesn't exist..."
        mkdir -p $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/

        echo "Copying SSH public key into Terraform module..."
        cp $(download_ssh_key.secureFilePath) $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/azure_vm_key.pub

        echo "Listing contents of modules/compute/ for verification:"
        ls -al $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/
      displayName: 'Prepare SSH Public Key for Terraform'

    # =========================
    # 4️⃣ Download Terraform variables file (dev.tfvars.txt) from Secure Files
    # =========================
    - task: DownloadSecureFile@1
      name: download_tfvars
      inputs:
        secureFile: 'dev.tfvars.txt'
      displayName: 'Download Terraform Variable File'
      # After this step, dev.tfvars.txt is at: $(download_tfvars.secureFilePath)

    # =========================
    # 5️⃣ Copy & rename dev.tfvars into Terraform working directory
    # =========================
    - script: |
        echo "Copying dev.tfvars file to Terraform working directory..."
        cp $(download_tfvars.secureFilePath) $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars

        echo "Verify dev.tfvars exists:"
        ls -al $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars
      displayName: 'Prepare dev.tfvars for Terraform'

    # =========================
    # 6️⃣ Terraform Init, Plan, and Apply
    # =========================
    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, and Apply'
      inputs:
        azureSubscription: 'arm-epicbook-spn' # Your Azure Service Connection
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/epicbook-infra  # <-- folder containing your .tf files
        inlineScript: |
          echo "Listing Terraform files in working directory:"
          ls -al

          echo "Initializing Terraform..."
          terraform init -input=false

          echo "Planning Terraform changes..."
          terraform plan -input=false -var-file=dev.tfvars

          echo "Applying Terraform..."
          terraform apply -input=false -auto-approve -var-file=dev.tfvars

    # =========================
    # 7️⃣ Clean up secure files (optional)
    # =========================
    - script: |
        echo "Cleaning up secure files..."
        rm -f $(System.DefaultWorkingDirectory)/epicbook-infra/modules/compute/azure_vm_key.pub
        rm -f $(System.DefaultWorkingDirectory)/epicbook-infra/dev.tfvars
      displayName: 'Clean Up Secure Files'
